/**
 * Generates src/components/icons/paths.ts from the design's icon set.
 *
 * The design specifies Google Material Symbols Outlined at weight 300. Instead of
 * loading the icon web font (large, render-blocking, flashes ligature text), the exact
 * weight-300 glyphs are inlined as SVG paths. Brand marks come from simple-icons.
 *
 * Run: npm run icons   (only needed when the icon list below changes)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const modules = fileURLToPath(new URL("../node_modules/", import.meta.url));
const materialDir = join(modules, "@material-symbols/svg-300/outlined");
const simpleIconsDir = join(modules, "simple-icons/icons");

const MATERIAL = [
  // UI
  "arrow_forward",
  "arrow_back",
  "menu",
  "close",
  "check",
  "check_circle",
  "error",
  "keyboard_arrow_down",
  "mail",
  "progress_activity",
  "pause",
  "play_arrow",
  // Orbit, services, ecosystem
  "person",
  "bar_chart",
  "campaign",
  "palette",
  "computer",
  "smart_toy",
  "database",
  "groups",
  "forum",
  "settings",
  "language",
  "query_stats",
  "monitoring",
  "extension",
  "hub",
  "badge",
  // Business-behind chips and floating tags
  "inbox",
  "calendar_month",
  "person_add",
  "payments",
  "contacts",
  "dns",
  "description",
  "account_tree",
  // "assessment" in the design font; renamed to "analytics" (same glyph) in the SVG set
  "analytics",
  "folder",
  "reply",
  "contract",
  "receipt_long",
  // Process steps
  "search",
  "task_alt",
  "play_circle",
  "visibility",
];

const SIMPLE_ICONS = { facebook: "facebook", youtube: "youtube", x: "x" };

// LinkedIn was removed from simple-icons at the brand owner's request; this is the
// standard "in" glyph from the last CC0 release, without the rounded-square frame.
const LINKEDIN =
  "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452z";

const pathOf = (svg, name) => {
  const d = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (d.length === 0) throw new Error(`No path found in ${name}`);
  return d.join("");
};

const material = Object.fromEntries(
  MATERIAL.map((name) => [
    name,
    pathOf(readFileSync(join(materialDir, `${name}.svg`), "utf8"), name),
  ]),
);

const brands = Object.fromEntries(
  Object.entries(SIMPLE_ICONS).map(([key, file]) => [
    key,
    pathOf(readFileSync(join(simpleIconsDir, `${file}.svg`), "utf8"), file),
  ]),
);
brands.linkedin = LINKEDIN;

const out = `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Material Symbols Outlined, weight 300 (Apache-2.0). Brand marks: simple-icons (CC0).

/** viewBox for Material Symbols glyphs */
export const MATERIAL_VIEWBOX = "0 -960 960 960";

export const materialPaths = ${JSON.stringify(material, null, 2)} as const;

/** viewBox for brand glyphs */
export const BRAND_VIEWBOX = "0 0 24 24";

export const brandPaths = ${JSON.stringify(brands, null, 2)} as const;
`;

writeFileSync(new URL("../src/components/icons/paths.ts", import.meta.url), out);

// Icons used inside client components, as individual constants. Importing these instead
// of the full map keeps every other glyph out of the browser bundle.
const UI = [
  "arrow_forward",
  "menu",
  "close",
  "check_circle",
  "error",
  "keyboard_arrow_down",
  "progress_activity",
  "pause",
  "play_arrow",
];
const camel = (s) => s.replace(/_(\w)/g, (_, c) => c.toUpperCase());
const ui = `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Material Symbols Outlined, weight 300 (Apache-2.0). viewBox "0 -960 960 960".
${UI.map((n) => `export const ${camel(n)} = ${JSON.stringify(material[n])};`).join("\n")}
`;
writeFileSync(new URL("../src/components/icons/ui-paths.ts", import.meta.url), ui);

console.log(
  `icons: ${MATERIAL.length} material, ${Object.keys(brands).length} brand, ${UI.length} ui`,
);
