/**
 * Generates src/components/brand/logo-paths.ts from the official logo
 * (src/assets/brand/quintbyte-logo.svg).
 *
 * The source file stacks the "qb" mark above the "quintbyte" wordmark and stores each
 * colour as a single compound path. The site needs the mark and wordmark separately
 * (horizontal lockup in the nav/footer, mark alone in the orbit and ecosystem), so the
 * sub-paths are split by position — the geometry itself is not altered.
 *
 * Run: npm run logo   (only needed if the official logo file changes)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = readFileSync(
  new URL("../src/assets/brand/quintbyte-logo.svg", import.meta.url),
  "utf8",
);

const paths = [...src.matchAll(/<path d="([^"]+)" fill="([^"]+)"/g)].map((m) => ({
  d: m[1],
  fill: m[2].toLowerCase(),
}));
if (paths.length !== 2) throw new Error(`Expected 2 paths in the logo, found ${paths.length}`);

// The wordmark baseline sits below y=326; the mark (including the q descender) above it.
const WORDMARK_TOP = 326;

const split = (d) => {
  const subpaths = d
    .split(/(?=M )/)
    .map((s) => s.trim())
    .filter(Boolean);
  const mark = [];
  const word = [];
  for (const sp of subpaths) {
    const ys = [...sp.matchAll(/-?\d+(?:\.\d+)? (-?\d+(?:\.\d+)?)/g)].map((m) => Number(m[1]));
    (Math.min(...ys) >= WORDMARK_TOP ? word : mark).push(sp);
  }
  return { mark: mark.join(" "), word: word.join(" ") };
};

const bbox = (ds) => {
  const xs = [];
  const ys = [];
  for (const d of ds) {
    for (const m of d.matchAll(/(-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?)/g)) {
      xs.push(Number(m[1]));
      ys.push(Number(m[2]));
    }
  }
  const x = Math.min(...xs);
  const y = Math.min(...ys);
  return `${x} ${y} ${Math.max(...xs) - x} ${Math.max(...ys) - y}`;
};

const cyan = paths.find((p) => p.fill !== "#000000");
const dark = paths.find((p) => p.fill === "#000000");
const c = split(cyan.d);
const k = split(dark.d);

const out = `// Generated by scripts/generate-logo.mjs from src/assets/brand/quintbyte-logo.svg.
// Official QuintByte logo geometry — do not edit or redraw by hand.
// Render with fill-rule="evenodd": the traced contours rely on it for the letter counters.

/** The logo's accent colour, as supplied in the official file. */
export const LOGO_CYAN = ${JSON.stringify(cyan.fill)};

export const mark = {
  viewBox: ${JSON.stringify(bbox([c.mark, k.mark]))},
  /** "b" — accent colour */
  accent: ${JSON.stringify(c.mark)},
  /** "q" — black on light backgrounds, light ink on dark backgrounds */
  ink: ${JSON.stringify(k.mark)},
} as const;

export const wordmark = {
  viewBox: ${JSON.stringify(bbox([c.word, k.word]))},
  /** "quint" — accent colour */
  accent: ${JSON.stringify(c.word)},
  /** "byte" — black on light backgrounds, light ink on dark backgrounds */
  ink: ${JSON.stringify(k.word)},
} as const;
`;

writeFileSync(new URL("../src/components/brand/logo-paths.ts", import.meta.url), out);
console.log("logo: mark", bbox([c.mark, k.mark]), "| wordmark", bbox([c.word, k.word]));

// App icons: the mark centred on the site's dark surface, with the black "q" in light ink.
const [mx, my, mw, mh] = bbox([c.mark, k.mark]).split(" ").map(Number);
const pad = mh * 0.22;
const side = mh + pad * 2;
const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${mx - (side - mw) / 2} ${my - pad} ${side} ${side}" fill-rule="evenodd">
  <rect x="${mx - (side - mw) / 2}" y="${my - pad}" width="${side}" height="${side}" rx="${side * 0.22}" fill="#05080d"/>
  <path d="${c.mark}" fill="${cyan.fill}"/>
  <path d="${k.mark}" fill="#eef4f8"/>
</svg>
`;
writeFileSync(new URL("../src/app/icon.svg", import.meta.url), iconSvg);

const { default: sharp } = await import("sharp");
await sharp(Buffer.from(iconSvg))
  .resize(180, 180)
  .png()
  .toFile(fileURLToPath(new URL("../src/app/apple-icon.png", import.meta.url)));
console.log("icons: src/app/icon.svg, src/app/apple-icon.png");
